services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ensenarte-backend:latest
    environment:
      - ENV=production
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
